version: '3.8'

services:
    df-web:
        build: ./
        environment:
            MONGO_URI: mongodb://mongo/digitalfarmer
        container_name: df-api
        hostname: df-api
        ports: 
            - 9000:9000
        depends_on:
            - mongo
        restart: unless-stopped
    
    mongo:
        image: mongo
        container_name: mongodb
        volumes:
            - data:/data/db
        ports:
            - 27017:27017
        restart: unless-stopped

volumes:
    data:


