name: Digital Farmer API CI

on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]


jobs:
  test:
    env:
      CI: true
      MONGO_URI: mongodb://localhost/digitalfarmer
      JWT_SECRET: some_jwt_secret
    strategy:
      fail-fast: true
      matrix:
        node-version: [14.x, 16.x,]
        mongodb-version: ['4.4']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{matrix.node-version}}
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.6.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
      - run: npm install
      - run: npm test
  
  deploy:
    env:
      DOCKER_USER: ${{secrets.DOCKER_USER}}
      DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      IMAGE_NAME: ${{secrets.DOCKER_USER}}/digital-farmer-api
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run:  echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin
      - name: Build docker image
        run: |
          echo ${{github.event.head_commit.message}}

          echo JWT_SECRET="$JWT_SECRET" >> .env

          IMAGE_NAME=$(echo $IMAGE_NAME | tr '[A-Z]' '[a-z]')

          echo IMAGE_NAME=$IMAGE_NAME

          docker build . -t $IMAGE_NAME
      
      - name: Push image to docker hub
        run: docker push $IMAGE_NAME
